USE ROLE SNOWFLAKE_INTELLIGENCE_ADMIN;
USE DATABASE AUTOMATED_INTELLIGENCE;

-- RAW SCHEMA
USE SCHEMA RAW;
SELECT COUNT(*) FROM RAW.ORDERS;
SELECT * FROM RAW.ORDERS LIMIT 10;

SELECT COUNT(*) AS ORDER_COUNT, SUM(TOTAL_AMOUNT) AS REVENUE
FROM AUTOMATED_INTELLIGENCE.RAW.ORDERS
WHERE ORDER_DATE >= DATEADD(DAY, -45, CURRENT_DATE);

SELECT COUNT(*) FROM RAW.ORDER_ITEMS;
SELECT * FROM RAW.ORDER_ITEMS LIMIT 10;

-- DBT_ANALYTICS SCHEMA
USE SCHEMA DBT_ANALYTICS;
SELECT * FROM DBT_ANALYTICS.CUSTOMER_LIFETIME_VALUE LIMIT 10;
SELECT * FROM DBT_ANALYTICS.PRODUCT_AFFINITY LIMIT 10;


-- Snowflake Postgres | Public Schema
-- cd /Users/ddesai/Apps/automated-intelligence/snowflake-postgres
-- ./psql.sh -c "SELECT PRIORITY, SUBJECT, SUBSTRING(DESCRIPTION, 1, 120) FROM PUBLIC.SUPPORT_TICKETS ORDER BY RANDOM() LIMIT 10;"
-- ./psql.sh -c "SELECT REVIEW_TITLE, SUBSTRING(REVIEW_TEXT,1,120) FROM PUBLIC.PRODUCT_REVIEWS ORDER BY RANDOM() LIMIT 10;"


-- pg_lake
USE SCHEMA PG_LAKE;
SELECT TABLE_SCHEMA, TABLE_NAME, IS_ICEBERG FROM INFORMATION_SCHEMA.TABLES WHERE table_name in ('SUPPORT_TICKETS', 'PRODUCT_REVIEWS') ORDER BY TABLE_SCHEMA;

-- snow sql -q "SELECT GET_DDL('TABLE', 'AUTOMATED_INTELLIGENCE.PG_LAKE.SUPPORT_TICKETS')" -c dash-builder-si
-- snow sql -q "SELECT GET_DDL('TABLE', 'AUTOMATED_INTELLIGENCE.PG_LAKE.PRODUCT_REVIEWS')" -c dash-builder-si
